# Generated by Django 4.2.7 on 2025-12-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='daily_t1_limit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='school',
            name='daily_t2_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='school',
            name='daily_t3_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='uservote',
            name='tier',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], default='T1', max_length=2),
        ),
        migrations.AddIndex(
            model_name='uservote',
            index=models.Index(fields=['user', 'vote_date', 'tier'], name='api_uservot_user_id_8a02a2_idx'),
        ),
    ]
