# Generated by Django 4.2.7 on 2025-12-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_school_daily_t1_limit_school_daily_t2_limit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'teacher', 'created_at'], name='api_rating_user_id_5f2754_idx'),
        ),
    ]
