# Generated by Django 4.2.7 on 2025-12-17 03:03

from django.db import migrations, models


def set_default_real_names(apps, schema_editor):
    """为现有用户设置默认真实姓名：不可用（No.1）、不可用（No.2）..."""
    User = apps.get_model('api', 'User')
    counter = 1
    for user in User.objects.filter(real_name__isnull=True):
        user.real_name = f'不可用（No.{counter}）'
        user.save(update_fields=['real_name'])
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prevent_duplicate_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='真实姓名'),
        ),
        migrations.RunPython(set_default_real_names, migrations.RunPython.noop),
    ]
