# Generated by Django 4.2.7 on 2025-12-17 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_real_name_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('is_featured', models.BooleanField(default=False, verbose_name='神评')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-likes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCommentInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'comment'], name='api_usercom_user_id_a2441f_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['rating', 'parent_comment'], name='api_comment_rating__bce0df_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-is_featured', '-likes', '-created_at'], name='api_comment_is_feat_0b029b_idx'),
        ),
    ]
