# Generated by Django 4.2.7 on 2025-12-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_comment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInteraction',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercommentinteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercommentinteraction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='usercommentinteraction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_is_feat_0b029b_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_featured', '-created_at'], name='api_comment_is_feat_4d61a6_idx'),
        ),
        migrations.DeleteModel(
            name='UserCommentInteraction',
        ),
        migrations.AddField(
            model_name='commentinteraction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.comment'),
        ),
        migrations.AddField(
            model_name='commentinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentinteraction',
            index=models.Index(fields=['user', 'comment'], name='api_comment_user_id_86cabe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentinteraction',
            unique_together={('user', 'comment')},
        ),
    ]
