# Generated by Django 4.2.7 on 2025-12-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_comment_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_rating__bce0df_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_is_feat_4d61a6_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='神评'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300, verbose_name='评论内容'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['rating', '-created_at'], name='api_comment_rating__76748d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='api_comment_user_id_86e7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['is_featured', '-created_at'], name='api_rating_is_feat_4c18c0_idx'),
        ),
    ]
