# Generated by Django 4.2.7 on 2025-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_comment_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='commentinteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentinteraction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentinteraction',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='神评'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['is_featured', '-created_at'], name='api_rating_is_feat_4c18c0_idx'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentInteraction',
        ),
    ]
