# Generated by Django 4.2.7 on 2025-12-17 12:33

from django.db import migrations, models


def add_is_featured_if_not_exists(apps, schema_editor):
    """安全地添加 is_featured 字段（如果不存在）"""
    db = schema_editor.connection.alias
    db_engine = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        field_exists = False
        
        if db_engine == 'postgresql':
            # PostgreSQL 检查方法
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = 'api_rating' 
                    AND column_name = 'is_featured'
                );
            """)
            field_exists = cursor.fetchone()[0]
        elif db_engine == 'sqlite':
            # SQLite 检查方法
            cursor.execute("PRAGMA table_info(api_rating);")
            columns = cursor.fetchall()
            field_exists = any(col[1] == 'is_featured' for col in columns)
        
        if not field_exists:
            # 添加字段（SQLite和PostgreSQL都支持）
            if db_engine == 'sqlite':
                cursor.execute("""
                    ALTER TABLE api_rating 
                    ADD COLUMN is_featured INTEGER NOT NULL DEFAULT 0;
                """)
            else:
                cursor.execute("""
                    ALTER TABLE api_rating 
                    ADD COLUMN is_featured BOOLEAN NOT NULL DEFAULT FALSE;
                """)
        
        # 检查索引是否已存在
        index_exists = False
        if db_engine == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND tablename = 'api_rating' 
                    AND indexname = 'api_rating_is_feat_4c18c0_idx'
                );
            """)
            index_exists = cursor.fetchone()[0]
        elif db_engine == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='index' AND name='api_rating_is_feat_4c18c0_idx';")
            index_exists = cursor.fetchone() is not None
        
        if not index_exists:
            # 添加索引
            if db_engine == 'sqlite':
                cursor.execute("""
                    CREATE INDEX api_rating_is_feat_4c18c0_idx 
                    ON api_rating (is_featured, created_at DESC);
                """)
            else:
                cursor.execute("""
                    CREATE INDEX api_rating_is_feat_4c18c0_idx 
                    ON api_rating (is_featured, created_at DESC);
                """)


def reverse_add_is_featured(apps, schema_editor):
    """反向操作：删除字段和索引"""
    db = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # 删除索引
        cursor.execute("DROP INDEX IF EXISTS api_rating_is_feat_4c18c0_idx;")
        # 删除字段
        cursor.execute("ALTER TABLE api_rating DROP COLUMN IF EXISTS is_featured;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_comment_system'),
    ]

    operations = [
        # 使用 RunPython 安全地添加 is_featured 字段
        migrations.RunPython(
            add_is_featured_if_not_exists,
            reverse_add_is_featured,
        ),
    ]
