# Generated by Django 4.2.7 on 2025-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_comment_system'),
    ]

    operations = [
        # 只添加 is_featured 字段到 Rating
        # 不删除 Comment 模型，因为 0009 会重新创建它们
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='神评'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['is_featured', '-created_at'], name='api_rating_is_feat_4c18c0_idx'),
        ),
    ]
