# Generated by Django 4.2.7 on 2025-12-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_comment_models_if_not_exist(apps, schema_editor):
    """安全地创建 Comment 和 CommentInteraction 模型（如果不存在）"""
    db = schema_editor.connection.alias
    db_engine = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        comment_exists = False
        interaction_exists = False
        
        if db_engine == 'postgresql':
            # PostgreSQL 检查方法
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'api_comment'
                );
            """)
            comment_exists = cursor.fetchone()[0]
            
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'api_commentinteraction'
                );
            """)
            interaction_exists = cursor.fetchone()[0]
        elif db_engine == 'sqlite':
            # SQLite 检查方法
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='api_comment';")
            comment_exists = cursor.fetchone() is not None
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='api_commentinteraction';")
            interaction_exists = cursor.fetchone() is not None
        
        # 如果表已存在，跳过创建
        if comment_exists and interaction_exists:
            return
    
    # 如果表不存在，使用 Django 的标准方式创建
    with schema_editor.connection.cursor() as cursor:
        if not comment_exists:
            # 创建 Comment 表
            if db_engine == 'sqlite':
                cursor.execute("""
                    CREATE TABLE api_comment (
                        comment_id INTEGER PRIMARY KEY AUTOINCREMENT,
                        content TEXT NOT NULL,
                        likes INTEGER NOT NULL DEFAULT 0,
                        dislikes INTEGER NOT NULL DEFAULT 0,
                        created_at DATETIME NOT NULL,
                        updated_at DATETIME NOT NULL,
                        parent_id INTEGER,
                        rating_id INTEGER NOT NULL,
                        user_id INTEGER NOT NULL,
                        FOREIGN KEY (parent_id) REFERENCES api_comment(comment_id) ON DELETE CASCADE,
                        FOREIGN KEY (rating_id) REFERENCES api_rating(rating_id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES api_user(id) ON DELETE CASCADE
                    );
                """)
            else:
                cursor.execute("""
                    CREATE TABLE api_comment (
                        comment_id SERIAL PRIMARY KEY,
                        content TEXT NOT NULL,
                        likes INTEGER NOT NULL DEFAULT 0,
                        dislikes INTEGER NOT NULL DEFAULT 0,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        parent_id INTEGER,
                        rating_id INTEGER NOT NULL,
                        user_id INTEGER NOT NULL,
                        FOREIGN KEY (parent_id) REFERENCES api_comment(comment_id) ON DELETE CASCADE,
                        FOREIGN KEY (rating_id) REFERENCES api_rating(rating_id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES api_user(id) ON DELETE CASCADE
                    );
                """)
            
            # 创建索引
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS api_comment_rating__76748d_idx 
                ON api_comment (rating_id, created_at DESC);
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS api_comment_user_id_86e7b0_idx 
                ON api_comment (user_id, created_at DESC);
            """)
        
        if not interaction_exists:
            # 创建 CommentInteraction 表
            if db_engine == 'sqlite':
                cursor.execute("""
                    CREATE TABLE api_commentinteraction (
                        interaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
                        interaction_type VARCHAR(10) NOT NULL,
                        created_at DATETIME NOT NULL,
                        comment_id INTEGER NOT NULL,
                        user_id INTEGER NOT NULL,
                        FOREIGN KEY (comment_id) REFERENCES api_comment(comment_id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES api_user(id) ON DELETE CASCADE,
                        UNIQUE (user_id, comment_id)
                    );
                """)
            else:
                cursor.execute("""
                    CREATE TABLE api_commentinteraction (
                        interaction_id SERIAL PRIMARY KEY,
                        interaction_type VARCHAR(10) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        comment_id INTEGER NOT NULL,
                        user_id INTEGER NOT NULL,
                        FOREIGN KEY (comment_id) REFERENCES api_comment(comment_id) ON DELETE CASCADE,
                        FOREIGN KEY (user_id) REFERENCES api_user(id) ON DELETE CASCADE,
                        UNIQUE (user_id, comment_id)
                    );
                """)
            
            # 创建索引
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS api_comment_user_id_86cabe_idx 
                ON api_commentinteraction (user_id, comment_id);
            """)


def reverse_create_comment_models(apps, schema_editor):
    """反向操作：删除表"""
    db = schema_editor.connection.alias
    db_engine = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        if db_engine == 'sqlite':
            # SQLite 不支持 CASCADE
            cursor.execute("DROP TABLE IF EXISTS api_commentinteraction;")
            cursor.execute("DROP TABLE IF EXISTS api_comment;")
        else:
            # PostgreSQL 支持 CASCADE
            cursor.execute("DROP TABLE IF EXISTS api_commentinteraction CASCADE;")
            cursor.execute("DROP TABLE IF EXISTS api_comment CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_comment_and_featured'),
    ]

    operations = [
        # 使用 RunPython 安全地创建 Comment 相关模型
        migrations.RunPython(
            create_comment_models_if_not_exist,
            reverse_create_comment_models,
        ),
    ]
